# Edit as UTF-8

# Debugging Level: 0 => Off; 1 => Only Errors; 2 => Only Errors and Warnings; 4 => Only Errors, Warnings and Information; -1 => All  (default is 1)
DEBUG_LEVEL=4
# DBMS Driver class  (mandatory)
JDBC_DRIVER=com.mysql.cj.jdbc.Driver
#JDBC_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
# DBMS Conection URL (mandatory)
JDBC_URL=jdbc:mysql://localhost:3306/BricksCollector?sslMode=PREFERRED;connectTimeout=5000;socketTimeout=5000
#JDBC_URL=jdbc:sqlserver://localhost:1433;databaseName=BricksCollector;encrypt=true;integratedSecurity=true;lockTimeout=5000;socketTimeout=5000
# DBMS Conection Timeout, in milliseconds (default is 5000)
JDBC_CONNECT_TIMEOUT=5000
# DBMS login username
JDBC_USERNAME=BricksCollector_User
# DBMS login password
JDBC_PASSWORD=SecretPassword2!

